// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from single_language_interfaces.djinni

#import <Foundation/Foundation.h>
@class DBJavaOnlyListener;
@protocol DBObjcOnlyListener;
@protocol DBPyOnlyListener;


/**
 * Generating and compiling this makes sure other languages don't break
 * on references to interfaces they don't need.
 */
@protocol DBUsesSingleLanguageListeners

- (void)callForObjC:(nullable id<DBObjcOnlyListener>)l;

- (nullable id<DBObjcOnlyListener>)returnForObjC;

- (void)callForJava:(nullable DBJavaOnlyListener *)l;

- (nullable DBJavaOnlyListener *)returnForJava;

- (void)callForPy:(nullable id<DBPyOnlyListener>)l;

@end
